typography_spectrum: 0.30653701769188046
color:
  brandStrength: 0.9471326768398285
  lightness: 0.8074991598259658
  saturation: 0.39753216528333724
  rhythmicContrast: 0.5433326761703938
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.517871098825708
author:
  name: John-Paul Cunliffe
  email: john@amb-it-ion.com
  url: www.amb-it-ion.com
name: amb-it-ion
navigation:
  - name: 'Best of CH 2015: Instagram'
    id: 1f477a88-5287-4525-b992-c0772a81b196
    type: content
title: amb-it-ion
description: fullstack programmer/architect/requirements analyst
